<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="scp.targets.mock.SenderReceiverTest" tests="7" skipped="0" failures="0" errors="0" timestamp="2015-11-19T22:54:56" hostname="DESKTOP-PE2SLM5" time="1.031">
  <properties/>
  <testcase name="testExcessLoad" classname="scp.targets.mock.SenderReceiverTest" time="0.265"/>
  <testcase name="testRemoteUnknownFailure" classname="scp.targets.mock.SenderReceiverTest" time="0.125"/>
  <testcase name="testLocalTimeOut" classname="scp.targets.mock.SenderReceiverTest" time="0.016"/>
  <testcase name="testDataAccepted" classname="scp.targets.mock.SenderReceiverTest" time="0.125"/>
  <testcase name="testRemoteTimeOut" classname="scp.targets.mock.SenderReceiverTest" time="0.187"/>
  <testcase name="testFastSend" classname="scp.targets.mock.SenderReceiverTest" time="0.157"/>
  <testcase name="testDataRejected" classname="scp.targets.mock.SenderReceiverTest" time="0.141"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[pool-48-thread-1] WARN scp.impl.ReceiverInvoker - Dropping 2-th reception
[pool-48-thread-1] ERROR scp.impl.ReceiverInvoker - Failed to handle 1-th reception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at scp.impl.ReceiverInvoker.invokeHandler(ReceiverInvoker.java:99)
	at scp.impl.ReceiverInvoker.receive(ReceiverInvoker.java:86)
	at scp.targets.mock.InProcessCommunicationManagerImpl$4.lambda$send$11(InProcessCommunicationManagerImpl.java:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at scp.api.SenderReceiverTest$3.receive(SenderReceiverTest.java:146)
	at scp.api.SenderReceiverTest$3.receive(SenderReceiverTest.java:143)
	at scp.impl.ReceiverInvoker.lambda$invokeHandler$3(ReceiverInvoker.java:96)
	... 4 more
[Test worker] WARN scp.impl.SendRequester - Timed out handling 1-th send
[pool-48-thread-1] WARN scp.impl.ReceiverInvoker - Timed out handling 1-th reception
[Test worker] ERROR scp.impl.SendRequester - Failed to handle 1-th send
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at scp.impl.SendRequester.handleSend(SendRequester.java:71)
	at scp.impl.SendRequester.send(SendRequester.java:59)
	at scp.api.SenderReceiverTest.testFastSend(SenderReceiverTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at scp.targets.mock.InProcessCommunicationManagerImpl$4.send(InProcessCommunicationManagerImpl.java:165)
	at scp.impl.SendRequester.lambda$handleSend$4(SendRequester.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at scp.targets.mock.InProcessCommunicationManagerImpl$4.send(InProcessCommunicationManagerImpl.java:163)
	... 5 more
Caused by: java.lang.NullPointerException
	at scp.targets.mock.InProcessCommunicationManagerImpl$4.lambda$send$11(InProcessCommunicationManagerImpl.java:161)
	... 4 more
[Test worker] WARN scp.impl.SendRequester - Dropping 2-th send
]]></system-err>
</testsuite>
