<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - Class scp.targets.vertx.unclustered.RequesterResponderTest</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>Class scp.targets.vertx.unclustered.RequesterResponderTest</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/scp.targets.vertx.unclustered.html">scp.targets.vertx.unclustered</a> &gt; RequesterResponderTest</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">8</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">0</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">1</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.094s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox skipped" id="successRate">
<div class="percent">100%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Tests</a>
</li>
<li>
<a href="#tab1">Standard error</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="success">testDataUnavailable</td>
<td>0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">testExcessLoad</td>
<td>0.031s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">testFastRequest</td>
<td>0.016s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="skipped">testLocalTimeOut</td>
<td>-</td>
<td class="skipped">ignored</td>
</tr>
<tr>
<td class="success">testRemoteTimeOut</td>
<td>0.031s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">testRemoteUnknownFailure</td>
<td>0.016s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">testStaleData</td>
<td>0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">testSuccessfulRequest</td>
<td>0s</td>
<td class="success">passed</td>
</tr>
</table>
</div>
<div id="tab1" class="tab">
<h2>Standard error</h2>
<span class="code">
<pre>[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[vert.x-eventloop-thread-1] WARN scp.impl.ResponderInvoker - Dropping 2-th reception
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[vert.x-eventloop-thread-2] ERROR scp.impl.ResponderInvoker - Failed to handle 1-th reception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at scp.impl.ResponderInvoker.invokeHandler(ResponderInvoker.java:100)
	at scp.impl.ResponderInvoker.serviceRequest(ResponderInvoker.java:87)
	at scp.targets.vertx.CommunicationManagerImpl.lambda$registerResponder$17(CommunicationManagerImpl.java:163)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handleMessage(EventBusImpl.java:1121)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handle(EventBusImpl.java:1115)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$doReceive$179(EventBusImpl.java:755)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at scp.api.RequesterResponderTest$3.respond(RequesterResponderTest.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[Test worker] INFO scp.impl.RequestRequester - Handling stale 1-th response
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[Test worker] WARN scp.impl.RequestRequester - Dropping 2-th request
[Test worker] INFO scp.targets.vertx.CommunicationManagerImpl - Done setting up vertx eventbus
[vert.x-eventloop-thread-1] WARN scp.impl.ResponderInvoker - Timed out handling 1-th reception
</pre>
</span>
</div>
</div>
<div id="footer">
<p>Generated by 
<a href="http://www.gradle.org">Gradle 2.1</a> at Dec 4, 2015 7:30:11 PM</p>
</div>
</div>
</body>